name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools libffi-dev libssl-dev libjpeg-dev zlib1g-dev libncurses5 libncurses5-dev libsqlite3-dev libgmp-dev
          python3 -m pip install --upgrade pip
          pip install cython virtualenv
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@3.1.3
        with:
          name: app-release
          path: bin/*.apk
