name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
        pip3 install --upgrade pip
        pip3 install buildozer Cython
        sudo apt install -y libffi-dev libssl-dev libsqlite3-dev zlib1g-dev             libncurses5-dev libncursesw5-dev libreadline6-dev libgdbm-dev             libbz2-dev libexpat1-dev liblzma-dev

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: kivytestgame-apk
        path: bin/*.apk